# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from conect_banco import mostrar_junta_diagonal,adicionar_professo_na_junta,mostrar_membros_all


class Ui_adicioanar_membro_diagonal(QtWidgets.QWidget):
    def __init__(self,parent=None):
        super().__init__()
        self.parent=parent
        self.setupUi(self)
    def setupUi(self, Widget):
        Widget.setObjectName("membros_inicial")
        Widget.resize(300, 289)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Widget.sizePolicy().hasHeightForWidth())
        Widget.setSizePolicy(sizePolicy)
        self.layoutWidget = QtWidgets.QWidget(parent=Widget)
        self.layoutWidget.setObjectName("layoutWidget")
        self.Layout_principal = QtWidgets.QVBoxLayout(Widget)
        self.Layout_principal.setContentsMargins(0, 0, 0, 0)
        self.Layout_principal.setObjectName("Layout_principal")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.Layout_principal.addWidget(self.label)
        self.Layout_pesquisar = QtWidgets.QHBoxLayout()
        self.Layout_pesquisar.setObjectName("Layout_pesquisar")
        self.comboBox = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.Layout_pesquisar.addWidget(self.comboBox)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.Layout_pesquisar.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.Layout_pesquisar.addWidget(self.pushButton)
        self.Layout_principal.addLayout(self.Layout_pesquisar)
        self.layout_list_adicionar = QtWidgets.QHBoxLayout()
        self.layout_list_adicionar.setObjectName("layout_list_adicionar")
        self.layout_texto_integrantes = QtWidgets.QVBoxLayout()
        self.layout_texto_integrantes.setObjectName("layout_texto_integrantes")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.layout_texto_integrantes.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layout_texto_integrantes.addItem(spacerItem)
        self.layout_list_adicionar.addLayout(self.layout_texto_integrantes)
        self.listWidget = QtWidgets.QListWidget(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName("listWidget")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.layout_list_adicionar.addWidget(self.listWidget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layout_list_adicionar.addItem(spacerItem1)
        self.Layout_principal.addLayout(self.layout_list_adicionar)
        self.Layou_botao_salvar = QtWidgets.QHBoxLayout()
        self.Layou_botao_salvar.setObjectName("Layou_botao_salvar")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.Layou_botao_salvar.addWidget(self.pushButton_3)
        self.Layout_principal.addLayout(self.Layou_botao_salvar)
        self.filtrados_nome_id={}
        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.label.setText(_translate("Widget", "Adicionar Integrante em Junta Diagonal"))
        self.comboBox.addItems(["NOME","IDENTIDADE","CPF"])
        self.pushButton.setText(_translate("Widget", "BUSCAR"))
        self.label_2.setText(_translate("Widget", "Integrantes"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_3.setText(_translate("Widget", "Adicionar"))
        self.pushButton.clicked.connect(self.buscar)          # BUSCAR  #
        self.pushButton_3.clicked.connect(self.inserir_junta_diagonal)   # Salvar
        self.dicionario_nome_id={}
        self.listWidget.clicked.connect(self.mostrar_item_selecionao)
        self.carregar_membros()
    def mostrar_item_selecionao(self):
        item = self.listWidget.currentItem()
        if item:
            self.nome_selecionado=item.text()
    def inserir_junta_diagonal(self):
        msg = QtWidgets.QMessageBox()
        
        if self.nome_selecionado == '':
            msg.setWindowTitle("ERRO")
            msg.setText("Selecione um Professo")
            msg.setIcon(QtWidgets.QMessageBox.Icon.Information)
            msg.setStandardButtons(QtWidgets.QMessageBox.StandardButton.Ok)
            msg.exec()
            return


        id_selecionado = self.filtrados_nome_id[self.nome_selecionado]

        retorno = adicionar_professo_na_junta(id_professo=id_selecionado,nome=str(self.nome_selecionado))
        if retorno:
            msg.setWindowTitle("Sucesso")
            msg.setText("Cadastro efetuado com sucesso")
            msg.setIcon(QtWidgets.QMessageBox.Icon.Information)
            msg.setStandardButtons(QtWidgets.QMessageBox.StandardButton.Ok)
            msg.exec()
        

            # 🔹 Remove da lista imediatamente
            item = self.listWidget.currentItem()
            if item:
                self.listWidget.takeItem(self.listWidget.row(item))

            # 🔹 Remove também do dicionário
            self.dicionario_nome_id.pop(self.nome_selecionado, None)

            if self.parent:
                self.parent.junta_diagonal_janela()
            else:
                msg.setWindowTitle("Erro")
                msg.setText("Erro ao cadastrar professo")
                msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
                msg.setStandardButtons(QtWidgets.QMessageBox.StandardButton.Ok)
                msg.exec()


    def carregar_membros(self):
        
        membros = mostrar_membros_all(estado="Professo")   # {id_professo: {...}}
        membros_junta = mostrar_junta_diagonal()           # {id_junta: {...}}

        # Pegar todos os IDs de professos que já estão na junta
        ids_junta = [dados['id_professo'] for dados in membros_junta.values()]

        filtrados_nome_id = {}
        for id_professo, dados in membros.items():
            if id_professo not in ids_junta:  # só adiciona se ainda não está na junta
                filtrados_nome_id[dados['nome']] = id_professo

        # Atualiza listWidget
        self.listWidget.clear()
        for i, nome in enumerate(filtrados_nome_id.keys()):
            self.listWidget.insertItem(i, nome)

        self.filtrados_nome_id = filtrados_nome_id


    def buscar(self):
        criterio = self.comboBox.currentText().lower()  # nome, identidade ou cpf
        termo = self.lineEdit.text().strip().lower()

        if not termo:
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Icon.Warning)
            msg.setWindowTitle("Aviso")
            msg.setText("Digite algo para pesquisar.")
            msg.exec()
            return

        membros = mostrar_membros_all(estado='Professo')
        filtrados = {}
        for nome, id_membro in self.dicionario_nome_id.items():
            if termo in str(membros[id_membro][criterio]).lower():
                filtrados[nome] = id_membro

        self.listWidget.clear()
        for i, membro in enumerate(filtrados.values()):
            self.listWidget.insertItem(i, str(membros[membro]['nome']))

        self.dicionario_nome_id = filtrados


if __name__ == "__main__":
       import sys
       app = QtWidgets.QApplication(sys.argv)
       Widget = QtWidgets.QWidget()
       ui = Ui_adicioanar_membro_diagonal()
       ui.setupUi(Widget)
       Widget.show()
       sys.exit(app.exec())




