# Form implementation generated from reading ui file 'cadastro_agregados.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from conect_banco import cadastrar_agregados
from PyQt6.QtWidgets import QMessageBox

class Ui_cadastro_agrgados(QtWidgets.QWidget):
    def __init__(self,parent=None):
        super().__init__()
        self.estado=''
        self.parent=parent
        self.setupUi(self)
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(623, 152)
        self.widget = QtWidgets.QWidget(parent=Widget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(Widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titulo = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.titulo.setFont(font)
        self.titulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.verticalLayout.addWidget(self.titulo)
        self.layout_nome = QtWidgets.QHBoxLayout()
        self.layout_nome.setObjectName("layout_nome")
        self.titulo_nome = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titulo_nome.setFont(font)
        self.titulo_nome.setObjectName("titulo_nome")
        self.layout_nome.addWidget(self.titulo_nome)
        self.entrada_nome = QtWidgets.QLineEdit(parent=self.widget)
        self.entrada_nome.setObjectName("entrada_nome")
        self.layout_nome.addWidget(self.entrada_nome)
        self.verticalLayout.addLayout(self.layout_nome)
        self.layout_telefone = QtWidgets.QHBoxLayout()
        self.layout_telefone.setObjectName("layout_telefone")
        self.titulo_telefone = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titulo_telefone.setFont(font)
        self.titulo_telefone.setObjectName("titulo_telefone")
        self.layout_telefone.addWidget(self.titulo_telefone)
        self.entrada_telefone = QtWidgets.QLineEdit(parent=self.widget)
        self.entrada_telefone.setObjectName("entrada_telefone")
        self.layout_telefone.addWidget(self.entrada_telefone)
        self.verticalLayout.addLayout(self.layout_telefone)
        self.layout_endereco = QtWidgets.QHBoxLayout()
        self.layout_endereco.setObjectName("layout_endereco")
        self.titulo_endereco = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titulo_endereco.setFont(font)
        self.titulo_endereco.setObjectName("titulo_endereco")
        self.layout_endereco.addWidget(self.titulo_endereco)
        self.entrada_endereco = QtWidgets.QLineEdit(parent=self.widget)
        self.entrada_endereco.setObjectName("entrada_endereco")
        self.layout_endereco.addWidget(self.entrada_endereco)
        self.verticalLayout.addLayout(self.layout_endereco)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cadastrar = QtWidgets.QPushButton(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cadastrar.sizePolicy().hasHeightForWidth())
        self.cadastrar.setSizePolicy(sizePolicy)
        self.cadastrar.setObjectName("cadastrar")
        self.horizontalLayout.addWidget(self.cadastrar)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.titulo.setText(_translate("Widget", "Cadastro de agregados"))
        self.titulo_nome.setText(_translate("Widget", "Nome Completo:"))
        self.titulo_telefone.setText(_translate("Widget", "Telefone:"))
        self.titulo_endereco.setText(_translate("Widget", "Endereço:"))
        self.cadastrar.setText(_translate("Widget", "Cadastrar"))
        self.cadastrar.clicked.connect(self.pegar_cadastrar)
    def pegar_cadastrar(self):
        nome=self.entrada_nome.text()
        endereco=self.entrada_endereco.text()
        telefone=self.entrada_telefone.text()
        cadastro=cadastrar_agregados(nome=nome,endereco=endereco,telefone=telefone)
        msg=QMessageBox()
        if not cadastro:
            msg.setIcon(QMessageBox.Icon.Information)
            msg.setWindowTitle("erro")
            msg.setText("Erro ao cadastrar no Banco de dados")
            msg.setStandardButtons(QMessageBox.StandardButton.Ok)
            msg.exec()
        else:
            msg.setIcon(QMessageBox.Icon.Information)
            msg.setWindowTitle("Sucesso")
            msg.setText("Castro efetuado com sucesso")
            msg.setStandardButtons(QMessageBox.StandardButton.Ok)
            if self.parent:
                self.parent.prencher_tabela()
            msg.exec()

    
