# Form implementation generated from reading ui file 'editar_menores.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from conect_banco_demo import editar_menores,buscar_nome_menor
from PyQt6.QtWidgets import QMessageBox
from datetime import datetime

class Ui_editar_menores(QtWidgets.QWidget):
    def __init__(self,nome_menor=str,parent=None):
        super().__init__()
        self.nome_menor=nome_menor
        self.parent=parent
        self.setupUi(self)
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.setEnabled(True)
        Widget.resize(739, 413)
        self.layoutWidget = QtWidgets.QWidget(parent=Widget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 40, 621, 349))
        self.layoutWidget.setObjectName("layoutWidget")
        self.Layout_principal = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.Layout_principal.setContentsMargins(0, 0, 0, 0)
        self.Layout_principal.setObjectName("Layout_principal")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.Layout_principal.addWidget(self.label)
        self.widget_cadastro_menor = QtWidgets.QWidget(parent=self.layoutWidget)
        self.widget_cadastro_menor.setObjectName("widget_cadastro_menor")
        self.layout_cadastro_menor = QtWidgets.QVBoxLayout(self.widget_cadastro_menor)
        self.layout_cadastro_menor.setObjectName("layout_cadastro_menor")
        self.layout_nome = QtWidgets.QHBoxLayout()
        self.layout_nome.setObjectName("layout_nome")
        self.titulo_nome = QtWidgets.QLabel(parent=self.widget_cadastro_menor)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titulo_nome.setFont(font)
        self.titulo_nome.setObjectName("titulo_nome")
        self.layout_nome.addWidget(self.titulo_nome)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget_cadastro_menor)
        self.lineEdit.setObjectName("lineEdit")
        self.layout_nome.addWidget(self.lineEdit)
        self.layout_cadastro_menor.addLayout(self.layout_nome)
        self.layout_nome_2 = QtWidgets.QHBoxLayout()
        self.layout_nome_2.setObjectName("layout_nome_2")
        self.titulo_data_nascimento = QtWidgets.QLabel(parent=self.widget_cadastro_menor)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titulo_data_nascimento.setFont(font)
        self.titulo_data_nascimento.setObjectName("titulo_data_nascimento")
        self.layout_nome_2.addWidget(self.titulo_data_nascimento)
        self.entrada_data_nascimneto = QtWidgets.QDateEdit(parent=self.widget_cadastro_menor)
        self.entrada_data_nascimneto.setObjectName("entrada_data_nascimneto")
        self.layout_nome_2.addWidget(self.entrada_data_nascimneto)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layout_nome_2.addItem(spacerItem)
        self.layout_cadastro_menor.addLayout(self.layout_nome_2)
        self.layout_nome_pai = QtWidgets.QHBoxLayout()
        self.layout_nome_pai.setObjectName("layout_nome_pai")
        self.titulo_pai = QtWidgets.QLabel(parent=self.widget_cadastro_menor)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titulo_pai.setFont(font)
        self.titulo_pai.setObjectName("titulo_pai")
        self.layout_nome_pai.addWidget(self.titulo_pai)
        self.entrada_nome_pai = QtWidgets.QLineEdit(parent=self.widget_cadastro_menor)
        self.entrada_nome_pai.setObjectName("entrada_nome_pai")
        self.layout_nome_pai.addWidget(self.entrada_nome_pai)
        self.layout_cadastro_menor.addLayout(self.layout_nome_pai)
        self.layout_nome_mae = QtWidgets.QHBoxLayout()
        self.layout_nome_mae.setObjectName("layout_nome_mae")
        self.titulo_mae = QtWidgets.QLabel(parent=self.widget_cadastro_menor)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titulo_mae.setFont(font)
        self.titulo_mae.setObjectName("titulo_mae")
        self.layout_nome_mae.addWidget(self.titulo_mae)
        self.entrada_nome_mae = QtWidgets.QLineEdit(parent=self.widget_cadastro_menor)
        self.entrada_nome_mae.setObjectName("entrada_nome_mae")
        self.layout_nome_mae.addWidget(self.entrada_nome_mae)
        self.layout_cadastro_menor.addLayout(self.layout_nome_mae)
        self.layout_seletor_responsavel = QtWidgets.QHBoxLayout()
        self.layout_seletor_responsavel.setObjectName("layout_seletor_responsavel")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_cadastro_menor)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.layout_seletor_responsavel.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(parent=self.widget_cadastro_menor)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.layout_seletor_responsavel.addWidget(self.comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layout_seletor_responsavel.addItem(spacerItem1)
        self.layout_cadastro_menor.addLayout(self.layout_seletor_responsavel)
        self.Layout_principal.addWidget(self.widget_cadastro_menor)
        self.widget_novo_responsavel = QtWidgets.QWidget(parent=self.layoutWidget)
        self.widget_novo_responsavel.setObjectName("widget_novo_responsavel")
        self.layout_outro_responsavel = QtWidgets.QVBoxLayout(self.widget_novo_responsavel)
        self.layout_outro_responsavel.setObjectName("layout_outro_responsavel")
        self.layout_nome_responsavel = QtWidgets.QHBoxLayout()
        self.layout_nome_responsavel.setObjectName("layout_nome_responsavel")
        self.titulo_responsavel = QtWidgets.QLabel(parent=self.widget_novo_responsavel)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titulo_responsavel.setFont(font)
        self.titulo_responsavel.setObjectName("titulo_responsavel")
        self.layout_nome_responsavel.addWidget(self.titulo_responsavel)
        self.entreda_nome_outro_responsavel = QtWidgets.QLineEdit(parent=self.widget_novo_responsavel)
        self.entreda_nome_outro_responsavel.setObjectName("entreda_nome_outro_responsavel")
        self.layout_nome_responsavel.addWidget(self.entreda_nome_outro_responsavel)
        self.layout_outro_responsavel.addLayout(self.layout_nome_responsavel)
        self.layout_telefone_responsavel = QtWidgets.QHBoxLayout()
        self.layout_telefone_responsavel.setObjectName("layout_telefone_responsavel")
        self.titulo_responsavel_2 = QtWidgets.QLabel(parent=self.widget_novo_responsavel)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titulo_responsavel_2.setFont(font)
        self.titulo_responsavel_2.setObjectName("titulo_responsavel_2")
        self.layout_telefone_responsavel.addWidget(self.titulo_responsavel_2)
        self.entreda_nome_outro_responsavel_2 = QtWidgets.QLineEdit(parent=self.widget_novo_responsavel)
        self.entreda_nome_outro_responsavel_2.setObjectName("entreda_nome_outro_responsavel_2")
        self.layout_telefone_responsavel.addWidget(self.entreda_nome_outro_responsavel_2)
        self.layout_outro_responsavel.addLayout(self.layout_telefone_responsavel)
        self.Layout_principal.addWidget(self.widget_novo_responsavel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.Layout_principal.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.label_3 = QtWidgets.QLabel(parent=self.widget_cadastro_menor)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)

        self.radioButton = QtWidgets.QRadioButton(parent=self.widget_cadastro_menor)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)

        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.widget_cadastro_menor)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_2.addWidget(self.radioButton_2)

        self.horizontalLayout_2.setStretch(2, 1)
        self.layout_cadastro_menor.addLayout(self.horizontalLayout_2)
        self.id=''
        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.label.setText(_translate("Widget", "Editar Menores"))
        self.titulo_nome.setText(_translate("Widget", "Nome Completo :"))
        self.titulo_data_nascimento.setText(_translate("Widget", "Data de Nascimento:"))
        self.titulo_pai.setText(_translate("Widget", "Nome  do Pai :"))
        self.titulo_mae.setText(_translate("Widget", "Nome da mãe :"))
        self.label_2.setText(_translate("Widget", "Responsavel :"))
        self.comboBox.setItemText(0, _translate("Widget", "Pai"))
        self.comboBox.setItemText(1, _translate("Widget", "Mãe"))
        self.comboBox.setItemText(2, _translate("Widget", "outro"))
        self.titulo_responsavel.setText(_translate("Widget", "Nome do responsavel"))
        self.titulo_responsavel_2.setText(_translate("Widget", "Telefone do responsavel"))
        self.pushButton.setText(_translate("Widget", "Salvar"))
        self.label_3.setText(_translate("Widget", "Ativo"))
        self.radioButton.setText(_translate("Widget", "SIM"))
        self.radioButton_2.setText(_translate("Widget", "NÃO"))
        self.entreda_nome_outro_responsavel.setVisible(False)
        self.titulo_responsavel.setVisible(False)
        self.comboBox.currentTextChanged.connect(self.outro_responsavel)
        menor=buscar_nome_menor(nome=self.nome_menor)
        if len(menor)== 0:
            print("menor não encotrado")
        else:
            self.id=menor['id_menor']
            self.lineEdit.setText(menor['nome'])
            data_nasc=menor['data_nascimento'].split('-')
            self.entrada_data_nascimneto.setDate(QtCore.QDate(int(data_nasc[0]),int(data_nasc[1]),int(data_nasc[2])))
            self.entrada_nome_pai.setText(menor['nome_pai'])
            self.entrada_nome_mae.setText(menor['nome_mae'])
            if self.comboBox.currentText() == "outro":
                        self.entreda_nome_outro_responsavel.text(menor['responsavel'])
            self.entreda_nome_outro_responsavel_2.setText(menor['telefone_responsavel'])
            if menor['ativo'] == 'sim':
                self.radioButton.setChecked(True)
            else:
                self.radioButton_2.setChecked(True)
        self.pushButton.clicked.connect(self.pegar_dados_e_salvar)

    def outro_responsavel(self):
        if self.comboBox.currentText() == "outro":
            self.entreda_nome_outro_responsavel.setVisible(True)
            self.titulo_responsavel.setVisible(True)
        else:
            self.entreda_nome_outro_responsavel.setVisible(False)
            self.titulo_responsavel.setVisible(False)

    def pegar_dados_e_salvar(self):
         nome=self.lineEdit.text()
         data_nascimento=self.entrada_data_nascimneto.date().toString("dd-MM-yyyy")
         nome_pai=self.entrada_nome_pai.text()
         nome_mae=self.entrada_nome_mae.text()
         responsavel=self.comboBox.currentText()
         outro_responsavel=self.entreda_nome_outro_responsavel.text()
         telefone_responsavel=self.entreda_nome_outro_responsavel_2.text()
        # Converte para datetime
         dia, mes, ano = data_nascimento.split("-")
         data_nasc = datetime.strptime(f"{dia}/{mes}/{ano}", "%d/%m/%Y").date()

        # Calcula idade
         hoje = datetime.today().date()
         idade = hoje.year - data_nasc.year
         if (hoje.month, hoje.day) < (data_nasc.month, data_nasc.day):
            idade -= 1
         ativo=True
         if idade <= 18:
            data_nascimento=self.entrada_data_nascimneto.date().toString("yyyy-MM-dd")
            if not self.radioButton.isChecked():
                ativo=False
            if responsavel == "Pai":
                outro_responsavel=nome_pai
            elif responsavel == "Mãe":
                outro_responsavel=nome_mae
            else:
                pass
            cadastro=editar_menores(id_menores=self.id,nome=nome,data_nasc=data_nascimento,nome_pai=nome_pai,nome_mãe=nome_mae,responsavel=outro_responsavel,telefone_responsavel=telefone_responsavel,ativo=ativo)
            if cadastro:
                msg=QMessageBox()
                msg.setIcon(QMessageBox.Icon.Information)
                msg.setWindowTitle("Sucesso")
                msg.setText("Salvo com sucesso")
                msg.setStandardButtons(QMessageBox.StandardButton.Ok)
                if self.parent:
                    self.parent.prencher_tabela()
                msg.exec()
            else:
                            
                            
                msg=QMessageBox()
                msg.setIcon(QMessageBox.Icon.Information)
                msg.setWindowTitle("erro")
                msg.setText("Erro ao Salvar no Banco de dados")
                msg.setStandardButtons(QMessageBox.StandardButton.Ok)
                msg.exec()

         else:
                msg=QMessageBox()
                msg.setIcon(QMessageBox.Icon.Information)
                msg.setWindowTitle("erro")
                msg.setText("Erro menor não pode ser maior de 18 anos")
                msg.setStandardButtons(QMessageBox.StandardButton.Ok)

                msg.exec()