# Form implementation generated from reading ui file 'edicao_professos.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from conect_banco import buscar_professo_por_nome,buscar_professo_transferido,baixar_arquivo_transferencia,salvar_dados_professo
from PyQt6.QtWidgets import QButtonGroup
from PyQt6.QtWidgets import QFileDialog,QMessageBox


class Ui_edicao_professos(QtWidgets.QWidget):
    def __init__(self,nome,parent=None):
        super().__init__()
        self.nome=nome
        self.parent=parent
        self.setupUi(self)
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1180, 216)
        self.layoutWidget = QtWidgets.QWidget(parent=Widget)
        self.layoutWidget.setObjectName("layoutWidget")
        self.layout_principal = QtWidgets.QVBoxLayout(Widget)
        self.layout_principal.setContentsMargins(0, 0, 0, 0)
        self.layout_principal.setObjectName("layout_principal")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.layout_principal.addWidget(self.label)
        self.layout_cadastro_principal = QtWidgets.QVBoxLayout()
        self.layout_cadastro_principal.setObjectName("layout_cadastro_principal")
        self.layout_1 = QtWidgets.QHBoxLayout()
        self.layout_1.setObjectName("layout_1")
        self.layout_nome = QtWidgets.QHBoxLayout()
        self.layout_nome.setObjectName("layout_nome")
        self.titulo_nome = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titulo_nome.setFont(font)
        self.titulo_nome.setObjectName("titulo_nome")
        self.layout_nome.addWidget(self.titulo_nome)
        self.nome_entrada = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.nome_entrada.setObjectName("nome_entrada")
        self.layout_nome.addWidget(self.nome_entrada)
        self.layout_1.addLayout(self.layout_nome)
        self.layout_endereco = QtWidgets.QHBoxLayout()
        self.layout_endereco.setObjectName("layout_endereco")
        self.endereo_nome = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.endereo_nome.setFont(font)
        self.endereo_nome.setObjectName("endereo_nome")
        self.layout_endereco.addWidget(self.endereo_nome)
        self.entrada_endereco = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.entrada_endereco.setObjectName("entrada_endereco")
        self.layout_endereco.addWidget(self.entrada_endereco)
        self.layout_1.addLayout(self.layout_endereco)
        self.layout_cadastro_principal.addLayout(self.layout_1)
        self.layout_2 = QtWidgets.QHBoxLayout()
        self.layout_2.setObjectName("layout_2")
        self.layoutidentidade = QtWidgets.QHBoxLayout()
        self.layoutidentidade.setObjectName("layoutidentidade")
        self.texto_identidade = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.texto_identidade.setFont(font)
        self.texto_identidade.setObjectName("texto_identidade")
        self.layoutidentidade.addWidget(self.texto_identidade)
        self.entrada_identidade = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.entrada_identidade.setObjectName("entrada_identidade")
        self.layoutidentidade.addWidget(self.entrada_identidade)
        self.layout_2.addLayout(self.layoutidentidade)
        self.layout_cpf = QtWidgets.QHBoxLayout()
        self.layout_cpf.setObjectName("layout_cpf")
        self.titulo_cpf = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titulo_cpf.setFont(font)
        self.titulo_cpf.setObjectName("titulo_cpf")
        self.layout_cpf.addWidget(self.titulo_cpf)
        self.entrada_cpf = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.entrada_cpf.setObjectName("entrada_cpf")
        self.layout_cpf.addWidget(self.entrada_cpf)
        self.layout_2.addLayout(self.layout_cpf)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.titulo_telefone = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titulo_telefone.setFont(font)
        self.titulo_telefone.setObjectName("titulo_telefone")
        self.horizontalLayout.addWidget(self.titulo_telefone)
        self.entrada_telefone = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.entrada_telefone.setObjectName("entrada_telefone")
        self.horizontalLayout.addWidget(self.entrada_telefone)
        self.layout_2.addLayout(self.horizontalLayout)
        self.layout_cadastro_principal.addLayout(self.layout_2)
        self.layout_3 = QtWidgets.QHBoxLayout()
        self.layout_3.setObjectName("layout_3")
        self.layout_nascimento = QtWidgets.QHBoxLayout()
        self.layout_nascimento.setObjectName("layout_nascimento")
        self.texto_data_nascimento = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.texto_data_nascimento.setFont(font)
        self.texto_data_nascimento.setObjectName("texto_data_nascimento")
        self.layout_nascimento.addWidget(self.texto_data_nascimento)
        self.entrada_data_nascimento = QtWidgets.QDateEdit(parent=self.layoutWidget)
        self.entrada_data_nascimento.setObjectName("entrada_data_nascimento")
        self.layout_nascimento.addWidget(self.entrada_data_nascimento)
        self.layout_3.addLayout(self.layout_nascimento)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.layout_3.addWidget(self.label_3)
        self.radioButton = QtWidgets.QRadioButton(parent=self.layoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.layout_3.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.layoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.layout_3.addWidget(self.radioButton_2)
        self.layout_data_ppfb = QtWidgets.QHBoxLayout()
        self.layout_data_ppfb.setObjectName("layout_data_ppfb")
        self.texto_data_ppfb = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.texto_data_ppfb.setFont(font)
        self.texto_data_ppfb.setObjectName("texto_data_ppfb")
        self.layout_data_ppfb.addWidget(self.texto_data_ppfb)
        self.entrada_data_ppfb = QtWidgets.QDateEdit(parent=self.layoutWidget)
        self.entrada_data_ppfb.setObjectName("entrada_data_ppfb")
        self.layout_data_ppfb.addWidget(self.entrada_data_ppfb)
        self.layout_3.addLayout(self.layout_data_ppfb)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layout_3.addItem(spacerItem)
        self.layout_transferido = QtWidgets.QHBoxLayout()
        self.layout_transferido.setObjectName("layout_transferido")
      # 🔹 Forma de admissão com ComboBox
        self.layout_forma_admissao = QtWidgets.QHBoxLayout()
        self.layout_forma_admissao.setObjectName("layout_forma_admissao")
        self.titulo_forma_admissao = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titulo_forma_admissao.setFont(font)
        self.titulo_forma_admissao.setObjectName("titulo_forma_admissao")
        self.layout_forma_admissao.addWidget(self.titulo_forma_admissao)

        self.forma_admissao = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.forma_admissao.setFont(font)
        self.layout_forma_admissao.addWidget(self.forma_admissao)

        self.layout_3.addLayout(self.layout_forma_admissao)

        # 🔹 Ativo com SIM/NÃO
        self.layout_ativo = QtWidgets.QHBoxLayout()
        self.layout_ativo.setObjectName("layout_ativo")
        self.titulo_ativo = QtWidgets.QLabel(parent=self.layoutWidget)
        self.titulo_ativo.setFont(font)
        self.titulo_ativo.setObjectName("titulo_ativo")
        self.layout_ativo.addWidget(self.titulo_ativo)

        self.ativo_sim = QtWidgets.QRadioButton(parent=self.layoutWidget)
        self.ativo_sim.setObjectName("ativo_sim")
        self.layout_ativo.addWidget(self.ativo_sim)

        self.ativo_nao = QtWidgets.QRadioButton(parent=self.layoutWidget)
        self.ativo_nao.setObjectName("ativo_nao")
        self.layout_ativo.addWidget(self.ativo_nao)

        self.layout_3.addLayout(self.layout_ativo)

        self.layout_3.addLayout(self.layout_transferido)
        self.layout_cadastro_principal.addLayout(self.layout_3)
        self.layout_principal.addLayout(self.layout_cadastro_principal)
        self.widget_igreja_traferida = QtWidgets.QWidget(parent=self.layoutWidget)
        self.widget_igreja_traferida.setObjectName("widget_igreja_traferida")
        self.layout_greja_trans_4 = QtWidgets.QHBoxLayout(self.widget_igreja_traferida)
        self.layout_greja_trans_4.setContentsMargins(-1, -1, 0, -1)
        self.layout_greja_trans_4.setObjectName("layout_greja_trans_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.titulo_igreja_transferida = QtWidgets.QLabel(parent=self.widget_igreja_traferida)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titulo_igreja_transferida.setFont(font)
        self.titulo_igreja_transferida.setObjectName("titulo_igreja_transferida")
        self.horizontalLayout_3.addWidget(self.titulo_igreja_transferida)
        self.entrada_igreja_transferida = QtWidgets.QLineEdit(parent=self.widget_igreja_traferida)
        self.entrada_igreja_transferida.setObjectName("entrada_igreja_transferida")
        self.horizontalLayout_3.addWidget(self.entrada_igreja_transferida)
        self.layout_greja_trans_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.titulo_tranferida = QtWidgets.QLabel(parent=self.widget_igreja_traferida)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titulo_tranferida.setFont(font)
        self.titulo_tranferida.setObjectName("titulo_tranferida")
        self.horizontalLayout_4.addWidget(self.titulo_tranferida)
        self.entrada_data_transferida = QtWidgets.QDateEdit(parent=self.widget_igreja_traferida)
        self.entrada_data_transferida.setObjectName("entrada_data_transferida")
        self.horizontalLayout_4.addWidget(self.entrada_data_transferida)
        self.layout_greja_trans_4.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layout_greja_trans_4.addItem(spacerItem3)
        self.label_2 = QtWidgets.QLabel(parent=self.widget_igreja_traferida)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.layout_greja_trans_4.addWidget(self.label_2)
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_igreja_traferida)
        self.pushButton.setObjectName("pushButton")
        self.layout_greja_trans_4.addWidget(self.pushButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layout_greja_trans_4.addItem(spacerItem4)
        self.pushButton_substituir = QtWidgets.QPushButton(parent=self.widget_igreja_traferida)
        self.pushButton_substituir.setObjectName("pushButton_substituir")
        self.layout_greja_trans_4.addWidget(self.pushButton_substituir)
        self.layout_principal.addWidget(self.widget_igreja_traferida)
        self.layout_botao_cadastrar = QtWidgets.QHBoxLayout()
        self.layout_botao_cadastrar.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.layout_botao_cadastrar.setSpacing(0)
        self.layout_botao_cadastrar.setObjectName("layout_botao_cadastrar")
        self.salvar = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.salvar.sizePolicy().hasHeightForWidth())
        self.salvar.setSizePolicy(sizePolicy)
        self.salvar.setObjectName("salvar")
        self.layout_botao_cadastrar.addWidget(self.salvar)
        self.layout_principal.addLayout(self.layout_botao_cadastrar)
        self.grupo_genero = QButtonGroup(self)
        self.grupo_genero.addButton(self.radioButton)    # Masculino
        self.grupo_genero.addButton(self.radioButton_2)  # Feminino
        self.grupo_genero.setExclusive(True)
        
        self.grupo_transferido = QButtonGroup(self)
        self.salvar.clicked.connect(self.pegar_dados_professo)
        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.label.setText(_translate("Widget", "Edição de professos"))
        self.titulo_nome.setText(_translate("Widget", "Nome completo :"))
        self.endereo_nome.setText(_translate("Widget", "endereço"))
        self.texto_identidade.setText(_translate("Widget", "Identidade"))
        self.titulo_cpf.setText(_translate("Widget", "CPF"))
        self.titulo_telefone.setText(_translate("Widget", "Telefone"))
        self.texto_data_nascimento.setText(_translate("Widget", "Data Nascimento"))
        self.label_3.setText(_translate("Widget", "Genero"))
        self.radioButton.setText(_translate("Widget", "Masculino"))
        self.radioButton_2.setText(_translate("Widget", "Femininno"))
        self.texto_data_ppfb.setText(_translate("Widget", "Data PPFB"))
        self.titulo_forma_admissao.setText(_translate("Widget", "Forma de Admissão"))
        self.titulo_ativo.setText(_translate("Widget", "Ativo"))
        self.ativo_sim.setText(_translate("Widget", "SIM"))
        self.ativo_nao.setText(_translate("Widget", "NÃO"))
        self.pushButton.setText(_translate("Widget", "Baixar arquivo"))
        self.pushButton_substituir.setText(_translate("Widget", "Substituir arquivo"))


        self.titulo_ativo.setText(_translate("Widget", "Ativo"))
        self.titulo_igreja_transferida.setText(_translate("Widget", "Igreja tranferida"))
        self.titulo_tranferida.setText(_translate("Widget", "Data de tranferencia"))
        self.label_2.setText(_translate("Widget", "Carta:"))
        self.pushButton.setText(_translate("Widget", "Baixar arquivo"))
        self.salvar.setText(_translate("Widget", "Salvar"))
        self.widget_igreja_traferida.setVisible(False)
        professo = buscar_professo_por_nome(self.nome)
        lista_admissao=["Profissão de fé","Profissão de fé e batismo","Carta de Transferencia","Jurisdição a Pedido","Jurisdição ex Oficio","Restauração do afastados","Designação do Presbiterio","Outros"]
        for i,item in enumerate(lista_admissao):
            self.forma_admissao.addItem("")
            self.forma_admissao.setItemText(i, _translate("Widget", str(item)))
        if professo:
            self.carregar_dados_professo(professo)
        self.pushButton_substituir.clicked.connect(self.selecionar_novo_pdf)
        self.pushButton.clicked.connect(self.visulizar_arquivo)
        
    def carregar_dados_professo(self, dados):
        # Campos de texto
        self.nome_entrada.setText(dados['nome'])
        self.entrada_endereco.setText(dados['endereco'])
        self.entrada_identidade.setText(dados['identidade'])
        self.entrada_cpf.setText(dados['cpf'])
        self.entrada_telefone.setText(dados['telefone'])

        # Datas (precisa converter string -> QDate)
        if dados['data_nasc']:
            from PyQt6.QtCore import QDate
            ano, mes, dia = map(int, dados['data_nasc'].split("/"))
            self.entrada_data_nascimento.setDate(QDate(ano, mes, dia))

        if dados['data_ppfb']:
            from PyQt6.QtCore import QDate
            ano, mes, dia = map(int, dados['data_ppfb'].split("/"))
            self.entrada_data_ppfb.setDate(QDate(ano, mes, dia))

        # Gênero (M ou F) → marcar e bloquear edição
        if dados['genero'] == 'Maculino':
            self.radioButton.setChecked(True)
        elif dados['genero'] == 'Feminino':
            self.radioButton_2.setChecked(True)

        # 🔒 desabilitar edição do gênero
        self.radioButton.setEnabled(False)
        self.radioButton_2.setEnabled(False)
        indice = self.forma_admissao.findText(dados['forma_admissao'])
        if indice >= 0:  # achou o valor na lista
            self.forma_admissao.setCurrentIndex(indice)

        if dados['ativo'] ==  'sim':
            self.ativo_sim.setChecked(True)
        else:
            self.ativo_nao.setChecked(True)
        if self.forma_admissao.currentText() == "Carta de Transferencia" : 
            self.widget_igreja_traferida.setVisible(True)
        else:
            self.widget_igreja_traferida.setVisible(False)
        self.forma_admissao.setEnabled(False)
        self.id=dados['id_professo']
        professo_transaferido=buscar_professo_transferido(id_professo=self.id)
        if professo_transaferido:
            self.entrada_igreja_transferida.setText(str(professo_transaferido['igreja_origem']))
            data_transf = professo_transaferido.get('data_transferencia')
            if data_transf:
                # Se for string no formato "YYYY-MM-DD"
                try:
                    ano, mes, dia = map(int, data_transf.split("/"))
                    self.entrada_data_transferida.setDate(QDate(ano, mes, dia))
                except ValueError:
                    # Se estiver em outro formato, tenta "DD/MM/YYYY"
                    dia, mes, ano = map(int, data_transf.split("/"))
                    self.entrada_data_transferida.setDate(QDate(ano, mes, dia))

    def visulizar_arquivo(self):
         baixar_arquivo_transferencia(self=self,id_professo=self.id)

    def selecionar_novo_pdf(self):
        arquivo, _ = QFileDialog.getOpenFileName(
            self,
            "Selecionar novo arquivo",
            "",
            "Arquivos PDF (*.pdf)"
        )
        if arquivo:
            try:
                # Lê o conteúdo do PDF como binário
                with open(arquivo, "rb") as f:
                    pdf_bytes = f.read()

                from igreja_presbiteriana.conect_banco import conn  # 🔹 use sua conexão com o banco
                conexao=conn 
                cursor = conexao.cursor()
                cursor.execute("""
                    UPDATE PROFESSOS_TRANSFERIDOS
                    SET CARTA = ?
                    WHERE ID_PROFESSO_TRANSFERIDO = ?;
                """, (pdf_bytes, self.id))
                conexao.commit()

                QMessageBox.information(
                    self,
                    "Sucesso",
                    f"O arquivo foi substituído com sucesso por:\n{arquivo}"
                )

            except Exception as e:
                QMessageBox.critical(self, "Erro", f"Erro ao substituir o arquivo:\n{e}")
    def pegar_dados_professo(self):
            """Pega os dados do formulário e retorna um dicionário."""
            from PyQt6.QtCore import QDate

            dados = {
                'id_professo': self.id,
                'nome': self.nome_entrada.text(),
                'endereco': self.entrada_endereco.text(),
                'identidade': self.entrada_identidade.text(),
                'cpf': self.entrada_cpf.text(),
                'telefone': self.entrada_telefone.text(),
                'data_nasc': self.entrada_data_nascimento.date().toString("yyyy/MM/dd"),
                'data_ppfb': self.entrada_data_ppfb.date().toString("yyyy/MM/dd"),
                'genero': 'Masculino' if self.radioButton.isChecked() else 'Feminino',
                'forma_admissao': self.forma_admissao.currentText(),
                'ativo': True if self.ativo_sim.isChecked() else False,
                'igreja_transferida': self.entrada_igreja_transferida.text(),
                'data_transferencia': self.entrada_data_transferida.date().toString("yyyy/MM/dd")
            }
            salvar_dados_professo(self=self,dados=dados)
            if self.parent:
                self.parent.prencher_tabela()


        
