# Form implementation generated from reading ui file 'editar_agregado.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from conect_banco import buscar_nome_agregado,editar_agregado


class Ui_editar_agregado(QtWidgets.QWidget):
    def __init__(self,nome=str,parent=None):
        super().__init__()
        self.nome=nome
        self.parent=parent
        self.setupUi(self)
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(693, 231)
        self.widget = QtWidgets.QWidget(parent=Widget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(Widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Titulo = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.Titulo.setFont(font)
        self.Titulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Titulo.setObjectName("Titulo")
        self.verticalLayout.addWidget(self.Titulo)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.titulo_nome = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titulo_nome.setFont(font)
        self.titulo_nome.setObjectName("titulo_nome")
        self.horizontalLayout.addWidget(self.titulo_nome)
        self.entrada_nome = QtWidgets.QLineEdit(parent=self.widget)
        self.entrada_nome.setObjectName("entrada_nome")
        self.horizontalLayout.addWidget(self.entrada_nome)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.titulo_endereco_2 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titulo_endereco_2.setFont(font)
        self.titulo_endereco_2.setObjectName("titulo_endereco_2")
        self.horizontalLayout_2.addWidget(self.titulo_endereco_2)
        self.entrada_endereco = QtWidgets.QLineEdit(parent=self.widget)
        self.entrada_endereco.setObjectName("entrada_endereco")
        self.horizontalLayout_2.addWidget(self.entrada_endereco)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.titulo_endereco = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titulo_endereco.setFont(font)
        self.titulo_endereco.setObjectName("titulo_endereco")
        self.horizontalLayout_3.addWidget(self.titulo_endereco)
        self.entrada_telefone = QtWidgets.QLineEdit(parent=self.widget)
        self.entrada_telefone.setObjectName("entrada_telefone")
        self.horizontalLayout_3.addWidget(self.entrada_telefone)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.titulo_ativo = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titulo_ativo.setFont(font)
        self.titulo_ativo.setObjectName("titulo_ativo")
        self.horizontalLayout_4.addWidget(self.titulo_ativo)
        self.entrada_sim = QtWidgets.QRadioButton(parent=self.widget)
        self.entrada_sim.setObjectName("entrada_sim")
        self.horizontalLayout_4.addWidget(self.entrada_sim)
        self.entrada_nao = QtWidgets.QRadioButton(parent=self.widget)
        self.entrada_nao.setObjectName("entrada_nao")
        self.horizontalLayout_4.addWidget(self.entrada_nao)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.Titulo.setText(_translate("Widget", "EDITAR AGREGADO"))
        self.titulo_nome.setText(_translate("Widget", "NOME:"))
        self.titulo_endereco_2.setText(_translate("Widget", "ENDEREÇO"))
        self.titulo_endereco.setText(_translate("Widget", "TELEFONE"))
        self.titulo_ativo.setText(_translate("Widget", "ATIVO:"))
        self.entrada_sim.setText(_translate("Widget", "SIM"))
        self.entrada_nao.setText(_translate("Widget", "NÃO"))
        self.pushButton.setText(_translate("Widget", "Salvar"))
        self.carregar_dados_agregado(nome_agregado=self.nome)
        self.pushButton.clicked.connect(self.salvar_dados_agregado)
    def carregar_dados_agregado(self, nome_agregado):
        dados = buscar_nome_agregado(nome_agregado)
        if not dados:
            QtWidgets.QMessageBox.warning(self, "Erro", "Agregado não encontrado.")
            return

        # Preenche os campos com os dados encontrados
        self.entrada_nome.setText(dados['nome'])
        self.entrada_telefone.setText(dados['telefone'])
        self.entrada_endereco.setText(dados['endereco'])

        if dados['ativo'].lower() == 'sim':
            self.entrada_sim.setChecked(True)
        else:
            self.entrada_nao.setChecked(True)

        # Guarda o ID do agregado para usar no salvamento
        self.id_agregado_atual = dados['id_agregado']

    def salvar_dados_agregado(self):
        try:
            # Verifica se um agregado foi carregado
            if not hasattr(self, 'id_agregado_atual'):
                QtWidgets.QMessageBox.warning(self, "Aviso", "Nenhum agregado carregado para edição.")
                return

            # Coleta os dados dos campos
            nome = self.entrada_nome.text().strip()
            telefone = self.entrada_telefone.text().strip()
            endereco = self.entrada_endereco.text().strip()
            ativo = self.entrada_sim.isChecked()

            # Validações básicas
            if not nome:
                QtWidgets.QMessageBox.warning(self, "Campo obrigatório", "O campo NOME não pode estar vazio.")
                return

            # Atualiza no banco
            sucesso = editar_agregado(
                id_agregado=self.id_agregado_atual,
                nome=nome,
                telefone=telefone,
                endereco=endereco,
                ativo=ativo
            )

            if sucesso:
                QtWidgets.QMessageBox.information(self, "Sucesso", "Agregado atualizado com sucesso.")
                if self.parent:
                 self.parent.prencher_tabela()
            else:
                QtWidgets.QMessageBox.critical(self, "Erro", "Ocorreu um erro ao atualizar o agregado.")

        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Erro", f"Ocorreu uma exceção: {str(e)}")

