# Form implementation generated from reading ui file 'gestao_funcoes.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from conect_banco import buscar_funcoes_por_area,deletar_funcao,autenticar_usuario
from adicionar_funcao import ui_adicionar_funcao
from editar_funcao_memebro import Ui_EditarMembro
class ClickableLabel(QtWidgets.QLabel):
        clicked = QtCore.pyqtSignal()
        def mousePressEvent(self, event):
            self.clicked.emit()
            super().mousePressEvent(event)

class ui_gestao_funcoes(QtWidgets.QWidget):
    def __init__(self,usuario):
        super().__init__()
        self.area=''
        self.usuario=usuario
        self.id_usuario=usuario['id']
        self.nome_usuario=usuario['nome']
        self.senha=usuario['senha']
        try:
            retorno=autenticar_usuario(self.nome_usuario,self.senha)
            if retorno[0]:
                self.setupUi(self)
            else:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
                msg.setText("Erro de autenticação")
                msg.setWindowTitle("Erro")
                msg.exec()
        except Exception as e:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
                msg.setText("Erro em executar a tela de inicio")
                msg.setWindowTitle("Erro")
                msg.exec()
                print("O erro e :",e)
        
    def setupUi(self, Widget):
        Widget.setObjectName("UI_gestao_funcoes")
        Widget.resize(936, 237)
        self.widget = QtWidgets.QWidget(parent=Widget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 791, 391))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(Widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.layout_alteracoes = QtWidgets.QHBoxLayout()
        self.layout_alteracoes.setObjectName("layout_alteracoes")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout_alteracoes.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_3 = ClickableLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = ClickableLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = ClickableLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = ClickableLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_8 = ClickableLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.label_7 = ClickableLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.layout_alteracoes.addLayout(self.verticalLayout_3)
        self.widget_membros = QtWidgets.QWidget(parent=self.widget)
        self.widget_membros.setObjectName("widget_membros")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_membros)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layout_tabela = QtWidgets.QVBoxLayout()
        self.layout_tabela.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.layout_tabela.setSpacing(11)
        self.layout_tabela.setObjectName("layout_tabela")
        self.titulo_membro = QtWidgets.QLabel(parent=self.widget_membros)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.titulo_membro.setFont(font)
        self.titulo_membro.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titulo_membro.setObjectName("titulo_membro")
        self.layout_tabela.addWidget(self.titulo_membro)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.widget_membros)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.layout_tabela.addWidget(self.tableWidget)
        self.layout_tabela.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.layout_tabela)
        self.layout_adicinar_remover_alterar = QtWidgets.QVBoxLayout()
        self.layout_adicinar_remover_alterar.setObjectName("layout_adicinar_remover_alterar")
        spacerItem = QtWidgets.QSpacerItem(20, 32, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layout_adicinar_remover_alterar.addItem(spacerItem)
        self.adicionar = QtWidgets.QPushButton(parent=self.widget_membros)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.adicionar.setFont(font)
        self.adicionar.setObjectName("adicionar")
        self.layout_adicinar_remover_alterar.addWidget(self.adicionar)
        self.adicionar_2 = QtWidgets.QPushButton(parent=self.widget_membros)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.adicionar_2.setFont(font)
        self.adicionar_2.setObjectName("adicionar_2")
        self.layout_adicinar_remover_alterar.addWidget(self.adicionar_2)
        self.remover = QtWidgets.QPushButton(parent=self.widget_membros)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.remover.setFont(font)
        self.remover.setObjectName("remover")
        self.layout_adicinar_remover_alterar.addWidget(self.remover)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.layout_adicinar_remover_alterar.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.layout_adicinar_remover_alterar)
        self.layout_alteracoes.addWidget(self.widget_membros)
        self.verticalLayout.addLayout(self.layout_alteracoes)
        self.widget_membros.setVisible(False)
        self.label_3.clicked.connect(self.louvor)
        self.label_4.clicked.connect(self.eventos_especias)
        self.label_5.clicked.connect(self.cozinha)
        self.label_6.clicked.connect(self.escola_domical)
        self.label_7.clicked.connect(self.Dep_infantil)
        self.label_8.clicked.connect(self.ministerio_oracao)
        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.label.setText(_translate("Widget", "Gestão de funçoes "))
        self.label_3.setText(_translate("Widget", "Louvor"))
        self.label_4.setText(_translate("Widget", "Evetos Especias"))
        self.label_5.setText(_translate("Widget", "Cozinha"))
        self.label_6.setText(_translate("Widget", "Escola Dominical"))
        self.label_7.setText(_translate("Widget", "Dep. infatil"))
        self.label_8.setText(_translate("Widget", "ministerio de orçâo"))
        self.titulo_membro.setText(_translate("Widget", "Membros compostos"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Widget", "NOME"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Widget", "FUNÇÃO"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Widget", "DATA ENTRADA"))
        self.adicionar.setText(_translate("Widget", "ADICIONAR"))
        self.adicionar_2.setText(_translate("Widget", "EDITAR"))
        self.remover.setText(_translate("Widget", "REMOVER"))
        self.widget_membros.setVisible(False)
        self.adicionar.clicked.connect(self.adicionar_membros_Area)
        self.adicionar_2.clicked.connect(self.editar_membro)
        self.remover.clicked.connect(self.remover_membro)
    def ver_membros(self):
        self.widget_membros.setVisible(True)
        membros_area=buscar_funcoes_por_area(area=self.area)
        if len(membros_area.keys()) > 0:
            self.tableWidget.setRowCount(0)
            for membro in membros_area.keys():
                rowPosition = self.tableWidget.rowCount()
                self.tableWidget.insertRow(rowPosition)
                self.tableWidget.setItem(rowPosition, 0, QtWidgets.QTableWidgetItem(membros_area[membro]['nome']))
                self.tableWidget.setItem(rowPosition, 1, QtWidgets.QTableWidgetItem(membros_area[membro]['funcao']))
                self.tableWidget.setItem(rowPosition, 2, QtWidgets.QTableWidgetItem(membros_area[membro]['data_entrada']))
        else:
             self.tableWidget.setRowCount(0)
    def adicionar_membros_Area(self):
        self.janela_adicionar=ui_adicionar_funcao(area=self.area,parent=self)
        self.janela_adicionar.show()
    def louvor(self):
        self.area="Louvor"
        self.ver_membros()
    def eventos_especias(self):
        self.area="Eventos Especias"
        self.ver_membros()
    def cozinha(self):
        self.area="Cozinha"
        self.ver_membros()
    def escola_domical(self):
        self.area="Escola Domical"
        self.ver_membros()
    def ministerio_oracao(self):
        self.area="Ministerio Oraçao"
        self.ver_membros()
    def Dep_infantil(self):
        self.area="Departamento Infatil"
        self.ver_membros()
    def editar_membro(self):
        try:
            nome=self.tableWidget.currentItem().text()
            membros_area=buscar_funcoes_por_area(area=self.area)
            for membro in membros_area.keys():
                 if membros_area[membro]['nome']==nome:
                     self.janela_editar=Ui_EditarMembro(membro=membros_area[membro],area=self.area,parent=self)
                     self.janela_editar.show()
            print(membros_area)
        except Exception as e:
            print(f"erro: {e}")
            QtWidgets.QMessageBox.warning(self, "Aviso", "Selecione um membro para editar.")
    def remover_membro(self):
        try:
            nome=self.tableWidget.currentItem().text()
            membros_area=buscar_funcoes_por_area(area=self.area)
            for membro in membros_area.keys():
                 if membros_area[membro]['nome']==nome:
                     retorno=deletar_funcao(id_funcao=membros_area[membro]['id'])
                     msg=QtWidgets.QMessageBox()
                     if retorno:
                            msg.setIcon(QtWidgets.QMessageBox.Icon.Information)
                            msg.setText(f"Membro {nome} removido com sucesso!")
                            msg.setWindowTitle("Sucesso")
                            msg.exec()
                            self.ver_membros()
                     else:
                            msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
                            msg.setText(f"Falha ao remover o membro {nome}.")
                            msg.setWindowTitle("Erro")
                            msg.exec()
        except Exception as e:
            print(f"erro: {e}")
            QtWidgets.QMessageBox.warning(self, "Aviso", "Selecione um membro para remover.")
