# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from gestao_finaceira import Ui_gestao_financeira
from membros import Ui_membros
from gestao_funcoes import ui_gestao_funcoes
from gestao_usuarios import ui_gestao_usaurios
from conect_banco import buscar_permissoes,autenticar_usuario,buscar_versiculo_atual
from opcoes import UI_opcoes
class ClickableLabel(QtWidgets.QLabel):
        clicked = QtCore.pyqtSignal()
        def mousePressEvent(self, event):
            self.clicked.emit()
            super().mousePressEvent(event)
      

class Ui_inicio(QtWidgets.QWidget):
    def __init__(self,usuario):
        super().__init__()
        self.usuario=usuario
        self.id_usuario=usuario['id']
        self.nome_usuario=usuario['nome']
        self.senha=usuario['senha']
        try:
            retorno=autenticar_usuario(self.nome_usuario,self.senha)
            if retorno[0]:
                self.setupUi(self)
            else:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
                msg.setText("Erro de autenticação")
                msg.setWindowTitle("Erro")
                msg.exec()
        except Exception as e:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
                msg.setText("Erro em executar a tela de inicio")
                msg.setWindowTitle("Erro")
                msg.exec()
                print("O erro e :",e)
        
    def setupUi(self, inicio):
        inicio.setObjectName("inicio")
        inicio.resize(1125, 710)
        self.layoutWidget = QtWidgets.QWidget(parent=inicio)
        self.layoutWidget.setObjectName("layoutWidget")
        self.layout_principal = QtWidgets.QVBoxLayout(inicio)
        self.layout_principal.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.layout_principal.setSpacing(14)
        self.layout_principal.setObjectName("layout_principal")
        self.layout_principal.setStretch(1, 0)
        self.texto_titulo = QtWidgets.QLabel(parent=self.layoutWidget)
        self.texto_titulo.setMaximumHeight(60)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        font.setBold(True)
        self.texto_titulo.setFont(font)
        self.texto_titulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.texto_titulo.setObjectName("texto_titulo")
        self.layout_principal.addWidget(self.texto_titulo)
        self.menu = QtWidgets.QWidget(parent=self.layoutWidget)
        self.menu.setObjectName("menu")
        self.Layou_menu = QtWidgets.QHBoxLayout(self.menu)
        self.Layou_menu.setObjectName("Layou_menu")
        self.widget_menu = QtWidgets.QWidget(parent=self.menu)
        self.widget_menu.setObjectName("widget_menu")
        self.layout_menu = QtWidgets.QVBoxLayout(self.widget_menu)
        self.layout_menu.setContentsMargins(1, 1, -1, 1)
        self.layout_menu.setSpacing(42)
        self.layout_menu.setObjectName("layout_menu")
        self.financas = ClickableLabel(parent=self.widget_menu)
        self.financas.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        self.financas.setFont(font)
        self.financas.setObjectName("financas")
        self.financas.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        
        self.gestao_funcoes = ClickableLabel(parent=self.widget_menu)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        self.gestao_funcoes.setFont(font)
        self.gestao_funcoes.setObjectName("gestao_funcoes")
        
        self.gestao_usaurios = ClickableLabel(parent=self.widget_menu)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        self.gestao_usaurios.setFont(font)
        self.gestao_usaurios.setObjectName("gestao_usaurios")

        self.opcoes = ClickableLabel(parent=self.widget_menu)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        self.opcoes.setFont(font)
        self.opcoes.setObjectName("opcoes_menu")
        self.opcoes.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        
    
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        self.cadastro_membros = ClickableLabel(parent=self.widget_menu)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        self.cadastro_membros.setFont(font)
        self.cadastro_membros.setObjectName("cadastro_membros")
        self.Layou_menu.addWidget(self.widget_menu)
        self.line = QtWidgets.QFrame(parent=self.menu)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.Layou_menu.addWidget(self.line)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.Layou_menu.addItem(spacerItem)
        self.layout_principal.addWidget(self.menu)
        self.layout_principal.setStretch(1, 0)
        self.versiculo = QtWidgets.QLabel(parent=self.layoutWidget)
        self.versiculo.setMaximumHeight(60)
        self.versiculo.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(True)
        self.versiculo.setFont(font)
        self.versiculo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.versiculo.setObjectName("versiculo")
        self.layout_principal.addWidget(self.versiculo)
        self.layout_principal.setStretch(0, 1)

        # adicionar label
        self.layout_menu.addWidget(self.financas)
        self.layout_menu.addWidget(self.cadastro_membros)
        self.layout_menu.addWidget(self.gestao_funcoes)
        self.layout_menu.addWidget(self.gestao_usaurios)
        self.layout_menu.addWidget(self.opcoes)
        spacer=QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.layout_menu.addItem(spacer)
        
        
        self.retranslateUi(inicio)
        QtCore.QMetaObject.connectSlotsByName(inicio)


    def retranslateUi(self, inicio):
        _translate = QtCore.QCoreApplication.translate
        versiculo=buscar_versiculo_atual()
        versiculo= str(versiculo[2]+" "+versiculo[1])
        self.texto_titulo.setText(_translate("inicio", "Igreja Presbiteriana do Bairo Novo amazonas"))
        self.financas.setText(_translate("inicio", "Finanças"))
        self.gestao_funcoes.setText(_translate("inicio", "Gestão de Funçoes"))
        self.gestao_funcoes.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.gestao_usaurios.setText(_translate("inicio", "Gestão de Usuarios"))
        self.gestao_usaurios.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cadastro_membros.setText(_translate("inicio", "Cadastro de membros"))
        self.opcoes.setText(_translate("inicio", "Opçoes"))
        self.versiculo.setText(_translate("inicio", versiculo))
        self.financas.clicked.connect(self.on_financas_clicked)
        self.cadastro_membros.clicked.connect(self.membro)
        self.gestao_funcoes.clicked.connect(self._gestao_funcoes)
        self.gestao_usaurios.clicked.connect(self._gestao_usuario)
        self.opcoes.clicked.connect(self._opcoes)
        self.financas_window = Ui_gestao_financeira(usuario=self.usuario)
        self.membros=Ui_membros(usuario=self.usuario)
        self.janela_gestao_funcoes=ui_gestao_funcoes(usuario=self.usuario)
        self.janela_gestao_usuarios=ui_gestao_usaurios(usuario=self.usuario)
        self.janela_opcoes=UI_opcoes(self)
        if self.usuario:
           try:
                permissoes=buscar_permissoes(self.id_usuario)
                self.financas.setVisible(permissoes['financa'])
                self.cadastro_membros.setVisible(permissoes['gestao_membros'])
                self.gestao_funcoes.setVisible(permissoes['gestao_funcoes'])
                self.gestao_usaurios.setVisible(permissoes['gestao_usuarios'])
           except Exception as e:
               print("Erro:",e)
        else:
           print("Usuário não fornecido")
           msg=QtWidgets.QMessageBox()
           msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
           msg.setText("Erro ao carregar as permissões do usuário!")
           msg.setWindowTitle("Erro de autenticação")
           msg.exec()
           QtCore.QTimer.singleShot(100, QtWidgets.QApplication.instance().quit)
           
           
        
    def on_financas_clicked(self):
          self.financas_window.setWindowTitle("Finanças - Igreja Presbiteriana do Bairro Amazonas")
          self.financas_window.show()
    def membro(self):
         self.membros.setWindowTitle("Gestão de Membros - Igreja Presbiteriana do Bairro Amazonas")
         self.membros.show()
    def _gestao_funcoes(self):
         self.janela_gestao_funcoes.setWindowTitle("Gestão de Funçoes de Membros - Igreja Presbiteriana do Bairro Amazonas")
         self.janela_gestao_funcoes.show()
    def _gestao_usuario(self):
         self.janela_gestao_usuarios.setWindowTitle("Gestão de Usuarios - Igreja Presbiteriana do Bairro Amazonas")
         self.janela_gestao_usuarios.show()
    def _opcoes(self):
         self.janela_opcoes.setWindowTitle("Opçoes - Igreja Presbiteriana do Bairro Amazonas")
         self.janela_opcoes.show()
    def atualizar_versiculo(self):
         versiculo=buscar_versiculo_atual()
         versiculo= str(versiculo[2]+" "+versiculo[1])
         self.versiculo.setText(versiculo)
