# Form implementation generated from reading ui file 'movimento_finaceiro.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from conect_banco import movimento_financeiro 
import re


class Ui_movimento_financeiro(QtWidgets.QWidget):
    def __init__(self,parent=None):
        super().__init__()
        self.parent=parent
        self.setupUi(self)
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(392, 150)
        self.widget = QtWidgets.QWidget(parent=Widget)
        self.widget.setObjectName("widget")
        self.layout_principal = QtWidgets.QVBoxLayout(Widget)
        self.layout_principal.setContentsMargins(0, 0, 0, 0)
        self.layout_principal.setObjectName("layout_principal")
        self.label = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layout_principal.addWidget(self.label)
        self.layout_tipo_de_movimento = QtWidgets.QHBoxLayout()
        self.layout_tipo_de_movimento.setObjectName("layout_tipo_de_movimento")
        self.titulo_movimento = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titulo_movimento.setFont(font)
        self.titulo_movimento.setObjectName("titulo_movimento")
        self.layout_tipo_de_movimento.addWidget(self.titulo_movimento)
        self.comboBox = QtWidgets.QComboBox(parent=self.widget)
        self.comboBox.setObjectName("comboBox")
        self.layout_tipo_de_movimento.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layout_tipo_de_movimento.addItem(spacerItem)
        self.layout_principal.addLayout(self.layout_tipo_de_movimento)
        self.widget_escolha_movimento = QtWidgets.QWidget(parent=self.widget)
        self.widget_escolha_movimento.setObjectName("widget_escolha_movimento")
        self.layout_esolha_movimento = QtWidgets.QVBoxLayout(self.widget_escolha_movimento)
        self.layout_esolha_movimento.setObjectName("layout_esolha_movimento")
        self.layout_valor = QtWidgets.QHBoxLayout()
        self.layout_valor.setObjectName("layout_valor")
        self.titulo_valor = QtWidgets.QLabel(parent=self.widget_escolha_movimento)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titulo_valor.setFont(font)
        self.titulo_valor.setObjectName("titulo_valor")
        self.layout_valor.addWidget(self.titulo_valor)
        self.entrada_valor = QtWidgets.QLineEdit(parent=self.widget_escolha_movimento)
        self.entrada_valor.setObjectName("entrada_valor")
        self.layout_valor.addWidget(self.entrada_valor)
        self.layout_esolha_movimento.addLayout(self.layout_valor)
        self.layout_tipo_movimento = QtWidgets.QHBoxLayout()
        self.layout_tipo_movimento.setObjectName("layout_tipo_movimento")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_escolha_movimento)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.layout_tipo_movimento.addWidget(self.label_2)
        self.tipo_movimento = QtWidgets.QComboBox(parent=self.widget_escolha_movimento)
        self.tipo_movimento.setObjectName("tipo_movimento")
        self.layout_tipo_movimento.addWidget(self.tipo_movimento)
        self.layout_esolha_movimento.addLayout(self.layout_tipo_movimento)
        self.layout_observacao = QtWidgets.QVBoxLayout()
        self.layout_observacao.setObjectName("layout_observacao")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_escolha_movimento)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.layout_observacao.addWidget(self.label_3)
        self.textEdit = QtWidgets.QTextEdit(parent=self.widget_escolha_movimento)
        self.textEdit.setObjectName("textEdit")
        self.layout_observacao.addWidget(self.textEdit)
        self.layout_esolha_movimento.addLayout(self.layout_observacao)
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_escolha_movimento)
        self.pushButton.setObjectName("pushButton")
        self.layout_esolha_movimento.addWidget(self.pushButton)
        self.layout_principal.addWidget(self.widget_escolha_movimento)
        self.widget_escolha_movimento.setVisible(False)
        self.comboBox.currentTextChanged.connect(self.ESCOLHA)
        self.retranslateUi(Widget)
        self.pushButton.clicked.connect(self.pegar_dados_salvar)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.label.setText(_translate("Widget", "MOVIMENTO FINANCEIRO"))
        self.titulo_movimento.setText(_translate("Widget", "movimento:"))
        self.comboBox.addItems(["ESCOLHA","ENTRADA","SAIDA"])
        self.titulo_valor.setText(_translate("Widget", "VALOR"))
        self.label_2.setText(_translate("Widget", "Tipo de movimento"))
        self.label_3.setText(_translate("Widget", "OBSERVAÇÃO:"))
        self.pushButton.setText(_translate("Widget", "SALVAR"))
    def ESCOLHA(self):
        if not self.comboBox.currentText() == "ESCOLHA":
           self.widget_escolha_movimento.setVisible(True)
           self.tipo_movimento.clear()
           if self.comboBox.currentText() == "ENTRADA":
             self.tipo_movimento.addItems(["Dízimos","Ofertas","Ofertas Missionárias:","Receitas Financeiras:","Empréstimos IPB / JPEF:","Parcerias:","Outras Receitas:"])
           elif self.comboBox.currentText() == "SAIDA":
              self.tipo_movimento.addItems(['Patrimônio:',"Causas Locais:","Evangelismo Local:","Missões:","Ação Social:","Sustento Pastoral:","Verba Presbiterial:","Dízimo ao Supremo Concílio:","Empréstimos IPB /JPEF:","Outras Despesas:"])
        else:
            self.widget_escolha_movimento.setVisible(False)
    def pegar_dados_salvar(self):
        data = QtCore.QDate.currentDate().toString("yyyy-MM-dd")
        movimento = self.comboBox.currentText()
        if movimento == "ENTRADA":
            movimento = True
        else:
            movimento = False
        
        tipo_movimento = self.tipo_movimento.currentText()
        valor = self.entrada_valor.text()
        valor=re.sub(r",",".",valor)
        obs = self.textEdit.toPlainText()
        retorno=movimento_financeiro(data,movimento,tipo_movimento,valor,obs)
        if retorno == True:
            msg=QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Icon.Information)
            msg.setText("Movimento salvo com sucesso!")
            msg.setWindowTitle("Sucesso")
            msg.exec()
            if self.parent:
                self.parent.preencher_tabela()
                self.parent.atualizar_valor()
        else:
            msg=QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
            msg.setText("Saldo insuficiente")
            msg.setWindowTitle("Erro")
            msg.exec()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_movimento_financeiro()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec())