# Form implementation generated from reading ui file 'tela_logon.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from inicio import Ui_inicio
from conect_banco import *


class ui_logon(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
    def setupUi(self, Widget):
        Widget.setObjectName("tela_logon")
        Widget.resize(500, 98)
        self.widget = QtWidgets.QWidget(parent=Widget)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.horizontalLayout__=QtWidgets.QHBoxLayout()
        image = QtGui.QImage()
        image.load("fundo.png")
        self.horizontalLayout__.addWidget(QtWidgets.QLabel())
        self.horizontalLayout__.itemAt(0).widget().setPixmap(QtGui.QPixmap.fromImage(image).scaled(100, 70, QtCore.Qt.AspectRatioMode.KeepAspectRatio, QtCore.Qt.TransformationMode.SmoothTransformation))
        self.label.setFont(font)
        self.label.setObjectName("titulo_tela_logon")
        self.horizontalLayout__.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout__)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.botao_olho = QtWidgets.QToolButton(self.lineEdit_2)
        self.botao_olho.setIcon(QtGui.QIcon.fromTheme("view-hidden"))  # Ícone padrão do sistema
        self.botao_olho.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.botao_olho.setStyleSheet("border: none; padding: 0px;")
        self.botao_olho.setGeometry(self.lineEdit_2.rect().right() - 25, 2, 22, 22)
        self.botao_olho.clicked.connect(self.toggle_senha)
        self.lineEdit_2.textChanged.connect(self.posicionar_botao_olho)


         
        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.label.setText(_translate("Widget", "Igreja Prebiteriana do Bairro Novo Amazonas"))
        self.label_2.setText(_translate("Widget", "USUARIO:"))
        self.label_3.setText(_translate("Widget", "SENHA:"))
        self.pushButton.setText(_translate("Widget", "ENTRAR"))
        self.pushButton.clicked.connect(self.entrar)
    def entrar(self):
        try:
            usuario = self.lineEdit.text()
            senha = self.lineEdit_2.text()
            retorno=autenticar_usuario(usuario, senha)
            print("usuario:",retorno)
            dados_usuario={'nome':usuario,'senha':senha,'id':retorno[1][0]}
            if retorno[0]:
                self.ui_inicio = Ui_inicio(usuario=dados_usuario)
                self.ui_inicio.show()
                Widget.close()
                
            else:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
                msg.setText("Usuário ou senha incorretos!")
                msg.setWindowTitle("Erro de autenticação")
                msg.exec()
        except Exception as e:
            print("erro:",e)
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
            msg.setText("Erro em encotrar usuario")
            msg.setWindowTitle("Erro de autenticação")
            msg.exec()
    def toggle_senha(self):
        """Alterna entre mostrar e ocultar a senha."""
        if self.lineEdit_2.echoMode() == QtWidgets.QLineEdit.EchoMode.Password:
            self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
            self.botao_olho.setIcon(QtGui.QIcon.fromTheme("view-visible"))
            self.botao_olho.setIcon(QtGui.QIcon("./olho.png"))
        else:
            self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
            self.botao_olho.setIcon(QtGui.QIcon.fromTheme("view-hidden"))
            self.botao_olho.setIcon(QtGui.QIcon("./olho.png"))

    def posicionar_botao_olho(self):
        """Mantém o botão do olho posicionado à direita."""
        rect = self.lineEdit_2.rect()
        self.botao_olho.move(rect.right() - 25, (rect.height() - 20) // 2)

if __name__ == "__main__":

    import sys
    app = QtWidgets.QApplication(sys.argv)
    with open("./estilo.qss", "r") as f:
        app.setStyleSheet(f.read())

    Widget = QtWidgets.QWidget()
    ui = ui_logon()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec())